Controllers/IssuesController.cs
using CourtHouse.Data;
using CourtHouse.Data.Repository;
using CourtHouse.Data.ViewModels;
using CourtHouse.Models;
using Emgu.CV;
using Emgu.CV.CvEnum;
using Emgu.CV.Face;
using Emgu.CV.Structure;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Mail;

namespace CourtHouse.Controllers
{
    [Authorize]
    public class IssuesController : Controller
    {
        public IRepository<RealtyContract> RealtyContract { get; }
        public UserManager<User> UserManager { get; }
        public IRepository<Region> Region { get; }
        public IRepository<Realty> Realty { get; }
        public IRepository<Beneficiary> Beneficiary { get; }
        public IRepository<Fees> Fees { get; }
        public IRepository<OfficialDocument> OfficialDocument { get; }
        public IWebHostEnvironment Hosting { get; }
        public IRepository<RealtyContractNote> RealtyContractNots { get; }
        public IRepositoryUser UserFun { get; }
        public FaceId FaceId { get; }

        public IssuesController(IRepository<RealtyContract> realtyContract, UserManager<User> userManager,
            IRepository<Region> region, IRepository<Realty> realty, IRepository<Beneficiary> beneficiary,
            IRepository<Fees> fees, IRepository<OfficialDocument> officialDocument, IWebHostEnvironment hosting,
            IRepository<RealtyContractNote> realtyContractNots, IRepositoryUser userFun, FaceId faceId)
        {
            RealtyContract = realtyContract;
            UserManager = userManager;
            Region = region;
            Realty = realty;
            Beneficiary = beneficiary;
            Fees = fees;
            OfficialDocument = officialDocument;
            Hosting = hosting;
            RealtyContractNots = realtyContractNots;
            UserFun = userFun;
            FaceId = faceId;
        }
        public ActionResult Index()
        {
            try
            {
                var username = UserManager.GetUserId(User);
                var VMReCoWILs = new VMRealtyContractWithList
                {
                    CheckContract = new List<RealtyContract>(),
                    EndContract = new List<RealtyContract>(),
                    NewContract = new List<RealtyContract>(),
                    ScheduleContract = new List<RealtyContract>(),
                    WaitPayContract = new List<RealtyContract>(),
                    WaitScheduleContract = new List<RealtyContract>(),
                    ScheduleContractToday = new List<RealtyContract>()
                };
                if (User.IsInRole("Admin"))
                {
                    var con = RealtyContract.All().OrderByDescending(a => a.startDate);
                    foreach (var item in con)
                    {
                        if (item.isChecked == false) VMReCoWILs.NewContract.Add(item);
                        if (item.isChecked == true && item.isAddFinance == false) VMReCoWILs.CheckContract.Add(item);
                        if (item.isAddFinance == true && item.isFinance == false) VMReCoWILs.WaitPayContract.Add(item);
                        if (item.isFinance == true && item.isJudge == false)
                        {
                            var c = Beneficiary.Search(item.id);
                            var b = false;
                            foreach (var ben in c)
                            {
                                if (ben.SessionDate.ToString() == "1/1/0001 12:00:00 AM")
                                {
                                    b = true;
                                    break;
                                }
                            }
                            if (b)
                            {
                                VMReCoWILs.WaitScheduleContract.Add(item);
                            }
                        }
                        if (item.isFinance == true && item.isJudge == false)
                        {
                            var c = Beneficiary.Search(item.id);
                            var b = true;
                            foreach (var ben in c)
                            {
                                if (ben.SessionDate.ToString() == "1/1/0001 12:00:00 AM")
                                {
                                    b = false;
                                    break;
                                }
                            }
                            foreach (var ben in c)
                            {
                                if (ben.SessionDate.Date == DateTime.Now.Date)
                                {
                                    VMReCoWILs.ScheduleContractToday.Add(ben.realtyContract);
                                }
                            }
                            if (b)
                            {
                                VMReCoWILs.ScheduleContract.Add(item);
                            }
                        }
                        if (item.isJudge == true) VMReCoWILs.EndContract.Add(item);                        
                    }
                    VMReCoWILs.NewContract.OrderBy(a => a.startDate);
                    VMReCoWILs.EndContract.OrderByDescending(a => a.startDate);
                    VMReCoWILs.CheckContract.OrderBy(a => a.startDate);
                    VMReCoWILs.ScheduleContract.OrderBy(a => a.startDate);
                    VMReCoWILs.ScheduleContractToday.OrderBy(a => a.startDate);
                    VMReCoWILs.WaitPayContract.OrderBy(a => a.startDate);
                    VMReCoWILs.WaitScheduleContract.OrderBy(a => a.startDate);                   
                    return View(VMReCoWILs);
                }
                if (User.IsInRole("LocalAdmin"))
                {
                    var con = RealtyContract.Search(UserManager.GetUserId(User),"LocalAdmin").OrderByDescending(a => a.startDate);
                    foreach (var item in con)
                    {
                        if (item.isChecked == false) VMReCoWILs.NewContract.Add(item);
                        if (item.isChecked == true && item.isAddFinance == false) VMReCoWILs.CheckContract.Add(item);
                        if (item.isAddFinance == true && item.isFinance == false) VMReCoWILs.WaitPayContract.Add(item);
                        if (item.isFinance == true && item.isJudge == false)
                        {
                            var c = Beneficiary.Search(item.id);
                            var b = false;
                            foreach (var ben in c)
                            {
                                if (ben.SessionDate.ToString() == "1/1/0001 12:00:00 AM")
                                {
                                    b = true;
                                    break;
                                }
                            }
                            if (b)
                            {
                                VMReCoWILs.WaitScheduleContract.Add(item);
                            }
                        }
                        if (item.isFinance == true && item.isJudge == false)
                        {
                            var c = Beneficiary.Search(item.id);
                            var b = true;
                            foreach (var ben in c)
                            {
                                if (ben.SessionDate.ToString() == "1/1/0001 12:00:00 AM")
                                {
                                    b = false;
                                    break;
                                }
                            }
                            foreach (var ben in c)
                            {
                                if (ben.SessionDate.Date == DateTime.Now.Date)
                                {
                                    VMReCoWILs.ScheduleContractToday.Add(ben.realtyContract);
                                }
                            }
                            if (b)
                            {
                                VMReCoWILs.ScheduleContract.Add(item);
                            }
                        }
                        if (item.isJudge == true) VMReCoWILs.EndContract.Add(item);
                    }
                    VMReCoWILs.NewContract.OrderBy(a => a.startDate);
                    VMReCoWILs.EndContract.OrderByDescending(a => a.startDate);
                    VMReCoWILs.CheckContract.OrderBy(a => a.startDate);
                    VMReCoWILs.ScheduleContract.OrderBy(a => a.startDate);
                    VMReCoWILs.ScheduleContractToday.OrderBy(a => a.startDate);
                    VMReCoWILs.WaitPayContract.OrderBy(a => a.startDate);
                    VMReCoWILs.WaitScheduleContract.OrderBy(a => a.startDate);
                    return View(VMReCoWILs);
                }
                if (User.IsInRole("Checker"))
                {
                    var con = RealtyContract.Search(username, "Checker").OrderBy(b => b.isChecked).ThenBy(a => a.startDate);
                    VMReCoWILs.NewContract = con.ToList();
                    return View(VMReCoWILs);
                }
                if (User.IsInRole("Finance"))
                {
                    var con = RealtyContract.Search(username, "Finance").OrderBy(b => b.isFinance).ThenBy(a => a.startDate);
                    foreach (var item in con)
                    {
                        if (item.isChecked == true && item.isAddFinance == false) VMReCoWILs.NewContract.Add(item);
                        if (item.isAddFinance == true && item.isFinance == false) VMReCoWILs.WaitPayContract.Add(item);
                    }
                    VMReCoWILs.NewContract.OrderBy(a => a.startDate);

Controllers/RealtyController.cs
using CourtHouse.Data.Repository;
using CourtHouse.Data.ViewModels;
using CourtHouse.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;

namespace CourtHouse.Controllers
{
    [Authorize(Roles ="DataEntry")]
    public class RealtyController : Controller
    {
        public IRepository<Realty> Realty { get; }
        public IRepository<Region> Region { get; }
        public IRepository<User> Use { get; }
        public UserManager<User> UserManager { get; }
        public IRepository<RealtyNote> RealtyNote { get; }

        public RealtyController (IRepository<Realty> realty, IRepository<Region> region,IRepository<User> use,UserManager<User> userManager, IRepository<RealtyNote> realtyNote)
        {
            Realty = realty;
            Region = region;
            Use = use;
            UserManager = userManager;
            RealtyNote = realtyNote;
        }
        public ActionResult Index()
        {
            var u = Use.Find(UserManager.GetUserId(User));
            var r = Realty.Search(u.region.id.ToString());
            return View(r);
        }
        public ActionResult Details(string id)
        {
            var r = Realty.Find(id);
            return View(r);
        }
        public ActionResult Create(string con)
        {
            try
            {
                var real = Realty.Find(con);
                var VR = new VMRealty
                {
                    id = con,
                    regionList = Region.All().ToList()
                };
                if (real != null)
                {
                    VR.adress = real.adress;
                    VR.area = real.area;
                    VR.info = real.info;
                    VR.regionSelect = Region.Find(real.region.id.ToString()).id;
                    VR.isChecked = false;
                    VR.realtyType = real.realtyType;
                    VR.theFinancialValue = real.theFinancialValue;
                }                
                return View(VR);
            }
            catch
            {
                return View("Error");
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(VMRealty collection)
        {
            try
            {
                var u = UserManager.GetUserAsync(User).Result;
                var R = new Realty
                {
                    id = collection.id,
                    adress = collection.adress,
                    area = collection.area,
                    info = collection.info,
                    isChecked = false,
                    realtyType = collection.realtyType,
                    theFinancialValue = collection.theFinancialValue,
                    region = Region.Find(collection.regionSelect.ToString())                    
                };
                if (Realty.Find(R.id) == null)
                {
                    R.createBy = u;
                    Realty.Add(R);
                }
                else
                {
                    Realty.Update(R);
                    var NR = new RealtyNote
                    {
                        id = Guid.NewGuid().ToString(),
                        noteDate = DateTime.Now,
                        noteType = "Upate Realty",
                        realty = R,
                        user = u
                    };
                    RealtyNote.Add(NR);
                }               
                Realty.Save();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View("Error");
            }
        }
        public ActionResult Edit(string id)
        {
            var r = Realty.Find(id);
            var vmr = new VMRealty
            {
                adress = r.adress,
                area = r.area,
                id = r.id,
                info = r.info,
                isChecked = r.isChecked,
                realtyType = r.realtyType,
                regionList = Region.All().ToList(),
                regionSelect = r.region.id,
                theFinancialValue = r.theFinancialValue
            };
            return View(vmr);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(string id, VMRealty collection)
        {
            try
            {
                var r = Realty.Find(id);
                r.adress = collection.adress;
                r.area = collection.area;
                r.info = collection.info;
                r.isChecked = collection.isChecked;
                r.realtyType = collection.realtyType;
                r.region = Region.Find(collection.regionSelect.ToString());
                r.theFinancialValue = collection.theFinancialValue;
                Realty.Update(r);
                Realty.Save();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View("Error");
            }
        }
        public ActionResult Delete(string id)
        {
            var r = Realty.Find(id);
            return View(r);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(Realty collection)
        {
            try
            {
                Realty.Delete(collection);
                Realty.Save();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View("Error");
            }
        }
        public ActionResult AddRealty()
        {
            return PartialView("AddRealty", new Realty { });
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddRealty(Realty rea)
        {
            return RedirectToAction(nameof(Create), new { con = rea.id });
        }
    }
}

Views/Shared/_Layout.cshtml
@inject Microsoft.AspNetCore.Identity.UserManager<User> SignInManager
<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CourtHouse</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/css/Chart.css" rel="stylesheet" />
</head>
<body>
    <header>
        <partial name="_PartialNav" />
    </header>
    <div class="container-fluid" style="background-image: url('/img/bg3.jpg'); background-size:100% 100%; background-repeat: no-repeat; background-attachment: fixed; height: 77vh; width: 100%;">
        <main role="main">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - CourtHouse
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/Chart.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Layout2.cshtml
@inject Microsoft.AspNetCore.Identity.UserManager<User> SignInManager
<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CourtHouse</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/css/Chart.css" rel="stylesheet" />
</head>
<body>
    <header>
        <partial name="_PartialNav" />
    </header>
    <div class="container-fluid">
        <main role="main">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - CourtHouse
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/Chart.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_PartialNav.cshtml
@inject Microsoft.AspNetCore.Identity.UserManager<User> userManager
<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
    <div class="container">
        <img class=" navbar-toggler-icon h-25" src="~/img/icon.jpg" />
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index" style="font-size:1">القصر العدلي</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">الصفحة الرئيسية</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Issues" asp-action="Index">القضايا</a>
                </li>
               
                @if (User.IsInRole("DataEntry"))
                {
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Realty" asp-action="Index">انشاء عقار</a>
                    </li>
                }
                @if (User.IsInRole("Admin"))
                {
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="WayToCommunicate" asp-action="Index">طرق التواصل</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">موظفين</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="RegionInfo">تقييم عمل المحافظات</a>
                    </li>
                }
                @if (User.IsInRole("Admin") || User.IsInRole("LocalAdmin"))
                {
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="EmployeeInfo">تقييم الموظفين</a>
                    </li>
                }
            </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>